import React, { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

const translations = {
  en: {
    // Sidebar
    "Dashboard": "Dashboard",
    "Analytics": "Analytics",
    "Weather": "Weather",
    "Reports": "Reports",
    "Settings": "Settings",
    "AgriX Intelligence": "AgriX Intelligence",
    "Collapse": "Collapse",

    // System Status Bar
    "Edge AI Online": "Edge AI Online",
    "Satellite Sync Active": "Satellite Sync Active",
    "Sensors Active (100%)": "Sensors Active (100%)",
    "Weather Synced": "Weather Synced",
    "Last AI Analysis:": "Last AI Analysis:",

    // KPI Cards
    "Crop Health": "Crop Health",
    "Soil Moisture": "Soil Moisture",
    "Field Area": "Field Area",
    "Active Crop": "Active Crop",
    "Sugarcane, Wheat, Cotton, Rice": "Sugarcane, Wheat, Cotton, Rice",
    "15 Active Districts Monitored": "15 Active Districts Monitored",
    "Nominal VWC Saturation": "Nominal VWC Saturation",
    "Deep Sensor Core Saturation": "Deep Sensor Core Saturation",
    "Direct High-Resolution Boundary": "Direct High-Resolution Boundary",

    // Operational Metrics
    "Saturation Index": "Saturation Index",
    "Valve Status": "Valve Status",
    "Satellite Coverage": "Satellite Coverage",
    "Sensors Status": "Sensors Status",

    // AI Decision Center
    "Awaiting Field Target": "Awaiting Field Target",
    "Select a precision crop field polygon on the geospatial map to trigger Edge AI Decision center calculations.": "Select a precision crop field polygon on the geospatial map to trigger Edge AI Decision center calculations.",
    "Analyzing Field Telemetry...": "Analyzing Field Telemetry...",
    "Running AgriX Decision Models ({progress}%)": "Running AgriX Decision Models ({progress}%)",
    "AgriX Decision Center": "AgriX Decision Center",
    "Overview": "Overview",
    "Health": "Health",
    "Recommendation": "Recommendation",
    "History": "History",
    "AI Recommendation": "AI Recommendation",
    "Action Plan": "Action Plan",
    "Expected Impact": "Expected Impact",
    "Priority": "Priority",
    "Risk Level": "Risk Level",
    "Water Saving": "Water Saving",
    "Cost Saving": "Cost Saving",
    "AI Confidence": "AI Confidence",
    "Selected Field Summary": "Selected Field Summary",
    "Current Field Status": "Current Field Status",
    "Operational Status": "Operational Status",
    "Field Target:": "Field Target:",
    "Crop Stage:": "Crop Stage:",
    "Moisture level:": "Moisture level:",
    "NDVI reflectance:": "NDVI reflectance:",
    "Soil Silt profile:": "Soil Silt profile:",
    "Last Irrigation:": "Last Irrigation:",
    "AI Analysis Summary": "AI Analysis Summary",
    "Analyzing Field...": "Analyzing Field...",
    "AI Inference Confidence": "AI Inference Confidence",
    "Calculated using Sentinel-2 reflectance indices coupled with active edge soil hygrometer telemetry.": "Calculated using Sentinel-2 reflectance indices coupled with active edge soil hygrometer telemetry.",
    "Risk Profile": "Risk Profile",
    "Explainability (\"Why?\")": "Explainability (\"Why?\")",
    "Local Field Diagnostics Log": "Local Field Diagnostics Log",
    "Sat Index": "Sat Index",
    "Sensor Net": "Sensor Net",
    "Water Stress": "Water Stress",

    // Status Values
    "Healthy": "Healthy",
    "Moderate": "Moderate",
    "Critical": "Critical",
    "Open": "Open",
    "Closed": "Closed",
    "Online": "Online",
    "Offline": "Offline",
    "Vegetative": "Vegetative",
    "Flowering": "Flowering",
    "Seedling": "Seedling",
    "Harvest Ready": "Harvest Ready",
    "Low": "Low",
    "Medium": "Medium",
    "High": "High",

    // Weather Widget
    "Live Weather Data": "Live Weather Data",
    "Using Last Available Weather Data": "Using Last Available Weather Data",
    "Temperature": "Temperature",
    "Humidity": "Humidity",
    "Wind Speed": "Wind Speed",
    "Rain Probability": "Rain Probability",
    "Cloud Cover": "Cloud Cover",
    "Sunrise": "Sunrise",
    "Sunset": "Sunset",

    // Compare Farms / Analytics
    "Compare Farms": "Compare Farms",
    "Select Farm A": "Select Farm A",
    "Select Farm B": "Select Farm B",
    "Performance Comparison": "Performance Comparison",
    "Comparison Summary": "Comparison Summary",
    "Metrics": "Metrics",
    "Health Score": "Health Score",
    "NDVI Index": "NDVI Index",

    // Reports & Settings Page
    "Download PDF": "Download PDF",
    "Download CSV": "Download CSV",
    "Print": "Print",
    "Export Diagnostic Telemetry Logs": "Export Diagnostic Telemetry Logs",
    "System Configuration": "System Configuration",
    "Notifications": "Notifications",
    "Agricultural Alerts": "Agricultural Alerts",
    "unread diagnostic items": "unread diagnostic items",
    "No agricultural notifications active": "No agricultural notifications active",
    "Mark all as read": "Mark all as read",
    "Clear": "Clear",

    // Scenario Simulator
    "Scenario Simulator": "Scenario Simulator",
    "Awaiting Field Simulation": "Awaiting Field Simulation",
    "Select an active field target on the geospatial map to boot environmental scenario simulation tools.": "Select an active field target on the geospatial map to boot environmental scenario simulation tools.",
    "Reset Engine": "Reset Engine",
    "Simulated Inference": "Simulated Inference",
    "Default Inference": "Default Inference",
    "Recalculating AI Models...": "Recalculating AI Models...",
    "Yield prediction:": "Yield prediction:",
    "Yield Prediction": "Yield Prediction",
    "Risk rating:": "Risk rating:",
    "Water Saved:": "Water Saved:",
    "Cost Saved:": "Cost Saved:",
    "AI Confidence:": "AI Confidence:",
    "Rain Delayed 24h": "Rain Delayed 24h",
    "Sets rain forecast probability to 0% due to weather front shift.": "Sets rain forecast probability to 0% due to weather front shift.",
    "Temperature +3°C": "Temperature +3°C",
    "Simulates microclimate thermal stress adding 3°C.": "Simulates microclimate thermal stress adding 3°C.",
    "Moisture Decreases 10%": "Moisture Decreases 10%",
    "Simulates soil VWC moisture dropping by 10%.": "Simulates soil VWC moisture dropping by 10%.",
    "Water Supply Reduced 20%": "Water Supply Reduced 20%",
    "Forces dry irrigation channel flow, raising crop stress.": "Forces dry irrigation channel flow, raising crop stress.",
    "Heavy Rainfall Tomorrow": "Heavy Rainfall Tomorrow",
    "Forecasts 90% rain probability tomorrow.": "Forecasts 90% rain probability tomorrow.",

    // AI Insight Feed & System alerts
    "AI Insight Feed": "AI Insight Feed",
    "AI Summary": "AI Summary",
    "Summary": "Summary",
    "What-if Analysis": "What-if Analysis",
    "Current Scenario": "Current Scenario",
    "Field Health": "Field Health",
    "Crop Lifecycle": "Crop Lifecycle",
    "Irrigation Recommendation": "Irrigation Recommendation",
    "Fertilizer Recommendation": "Fertilizer Recommendation",
    "Disease Alert": "Disease Alert",
    "Weather Recommendation": "Weather Recommendation",
    "Satellite Analysis": "Satellite Analysis",
    "Vegetation Index": "Vegetation Index",
    "Sensor Status": "Sensor Status",
    "Telemetry Updated": "Telemetry Updated",
    "Success messages": "Success messages",
    "Loading messages": "Loading messages",
    "Empty state messages": "Empty state messages",

    // PDF and CSV export layouts
    "PRECISION WATER INTELLIGENCE REPORT": "PRECISION WATER INTELLIGENCE REPORT",
    "PRECISION TELEMETRY DIAGNOSTIC PROFILE": "PRECISION TELEMETRY DIAGNOSTIC PROFILE",
    "AI INTELLIGENCE DIAGNOSTIC DECISION": "AI INTELLIGENCE DIAGNOSTIC DECISION",
    "Farm / Field ID:": "Farm / Field ID:",
    "Region State:": "Region State:",
    "District Hub:": "District Hub:",
    "Active Crop Profile:": "Active Crop Profile:",
    "Field Size Area:": "Field Size Area:",
    "Soil Profile Silt:": "Soil Profile Silt:",
    "NDVI Vegetation Index:": "NDVI Vegetation Index:",
    "Soil Moisture VWC:": "Soil Moisture VWC:",
    "Climate Conditions:": "Climate Conditions:",
    "Crop Health Rating:": "Crop Health Rating:",
    "AI Recommendation:": "AI Recommendation:",
    "Action Plan:": "Action Plan:",
    "Expected Impact:": "Expected Impact:",
    "Scenario Calibration:": "Scenario Calibration:",
    "Water Saving Estimate:": "Water Saving Estimate:",
    "Generated:": "Generated:",
    "System: Live Satellite Sync": "System: Live Satellite Sync",

    // Dynamic mock profiles
    "Awaiting Target Asset": "Awaiting Target Asset",
    "Select a precision field polygon on the geospatial map to initiate Edge AI telemetry and soil diagnostics.": "Select a precision field polygon on the geospatial map to initiate Edge AI telemetry and soil diagnostics.",
    "Edge AI Active": "Edge AI Active",
    "Crop Health Matrix": "Crop Health Matrix",
    "Vegetation density index rating.": "Vegetation density index rating.",
    "Saved": "Saved",
    "Telemetry Node:": "Telemetry Node:",
    "General Regional Averages": "General Regional Averages",
    "District": "District",
    "Historical Telemetry": "Historical Telemetry",
    "Field vegetation displays high chlorophyll concentration and optimized moisture index. Transpiration demands are normal. Irrigation hold is advised for the next 24 hours to prevent nutrient runoff.": "Field vegetation displays high chlorophyll concentration and optimized moisture index. Transpiration demands are normal. Irrigation hold is advised for the next 24 hours to prevent nutrient runoff.",
    "Moderate moisture deficit identified in shallow root zones. Weather forecasts indicate rising temperatures. Short-duration pulse valving is recommended to maintain volumetric saturation.": "Moderate moisture deficit identified in shallow root zones. Weather forecasts indicate rising temperatures. Short-duration pulse valving is recommended to maintain volumetric saturation.",
    "Critical soil dehydration anomalies verified. VWC has collapsed past warning thresholds (30%). High priority valving override is required immediately to mitigate yield degradation risks.": "Critical soil dehydration anomalies verified. VWC has collapsed past warning thresholds (30%). High priority valving override is required immediately to mitigate yield degradation risks.",
    "Hold Irrigation. VWC Saturation targets met.": "Hold Irrigation. VWC Saturation targets met.",
    "Pulse Irrigation (12 mins, Scheduled at 4 PM).": "Pulse Irrigation (12 mins, Scheduled at 4 PM).",
    "Trigger High-Flow Hydration Override immediately.": "Trigger High-Flow Hydration Override immediately.",

    // AI templates
    "Soil moisture is below the recommended threshold.": "Soil moisture is below the recommended threshold.",
    "Irrigation is recommended within 24 hours.": "Irrigation is recommended within 24 hours.",
    "Rain is expected tomorrow.": "Rain is expected tomorrow.",
    "Crop health is excellent.": "Crop health is excellent.",
    "Monitor for pest activity.": "Monitor for pest activity."
  },
  hi: {
    // Sidebar
    "Dashboard": "डैशबोर्ड",
    "Analytics": "विश्लेषण",
    "Weather": "मौसम",
    "Reports": "रिपोर्ट",
    "Settings": "सेटिंग्स",
    "AgriX Intelligence": "एग्रीएक्स इंटेलिजेंस",
    "Collapse": "संक्षिप्त करें",

    // System Status Bar
    "Edge AI Online": "एज एआई ऑनलाइन",
    "Satellite Sync Active": "सैटेलाइट सिंक सक्रिय",
    "Sensors Active (100%)": "सेंसर सक्रिय (100%)",
    "Weather Synced": "मौसम सिंक किया गया",
    "Last AI Analysis:": "अंतिम एआई विश्लेषण:",

    // KPI Cards
    "Crop Health": "फसल की स्थिति",
    "Soil Moisture": "मिट्टी की नमी",
    "Field Area": "खेत का क्षेत्रफल",
    "Active Crop": "सक्रिय फसल",
    "Sugarcane, Wheat, Cotton, Rice": "गन्ना, गेहूं, कपास, धान",
    "15 Active Districts Monitored": "15 सक्रिय जिले मॉनिटर",
    "Nominal VWC Saturation": "नाममात्र VWC संतृप्ति",
    "Deep Sensor Core Saturation": "गहरे सेंसर कोर संतृप्ति",
    "Direct High-Resolution Boundary": "सटीक क्षेत्र सीमा",

    // Operational Metrics
    "Saturation Index": "संतृप्ति सूचकांक",
    "Valve Status": "वाल्व की स्थिति",
    "Satellite Coverage": "सैटेलाइट कवरेज",
    "Sensors Status": "सेंसर की स्थिति",

    // AI Decision Center
    "Awaiting Field Target": "चयनित खेत की प्रतीक्षा",
    "Select a precision crop field polygon on the geospatial map to trigger Edge AI Decision center calculations.": "एज एआई डिसीजन सेंटर गणना शुरू करने के लिए मानचित्र पर एक खेत का चयन करें।",
    "Analyzing Field Telemetry...": "खेत का विश्लेषण किया जा रहा है...",
    "Running AgriX Decision Models ({progress}%)": "AgriX डिसीजन मॉडल चल रहे हैं ({progress}%)",
    "AgriX Decision Center": "AgriX डिसीजन सेंटर",
    "Overview": "अवलोकन",
    "Health": "स्वास्थ्य",
    "Recommendation": "सुझाव",
    "History": "इतिहास",
    "AI Recommendation": "एआई सुझाव",
    "Action Plan": "कार्य योजना",
    "Expected Impact": "अपेक्षित प्रभाव",
    "Priority": "प्राथमिकता",
    "Risk Level": "जोखिम का स्तर",
    "Water Saving": "पानी की बचत",
    "Cost Saving": "लागत की बचत",
    "AI Confidence": "एआई आत्मविश्वास",
    "Selected Field Summary": "चयनित खेत का विवरण",
    "Current Field Status": "खेत की वर्तमान स्थिति",
    "Operational Status": "परिचालन स्थिति",
    "Field Target:": "खेत का लक्ष्य:",
    "Crop Stage:": "फसल की अवस्था:",
    "Moisture level:": "नमी का स्तर:",
    "NDVI reflectance:": "एनडीवीआई परावर्तन:",
    "Soil Silt profile:": "मिट्टी का प्रकार:",
    "Last Irrigation:": "अंतिम सिंचाई:",
    "AI Analysis Summary": "एआई विश्लेषण सारांश",
    "Analyzing Field...": "खेत का विश्लेषण किया जा रहा है...",
    "AI Inference Confidence": "एआई अनुमान आत्मविश्वास",
    "Calculated using Sentinel-2 reflectance indices coupled with active edge soil hygrometer telemetry.": "सक्रिय मिट्टी हाइग्रोमीटर टेलीमेट्री के साथ मिलकर सेंटीनेल-2 सूचकांकों का उपयोग करके गणना की गई।",
    "Risk Profile": "जोखिम प्रोफ़ाइल",
    "Explainability (\"Why?\")": "व्याख्यात्मकता (\"क्यों?\")",
    "Local Field Diagnostics Log": "स्थानीय क्षेत्र नैदानिक लॉग",
    "Sat Index": "संतृप्ति",
    "Sensor Net": "सेंसर नेटवर्क",
    "Water Stress": "जल तनाव",

    // Status Values
    "Healthy": "स्वस्थ",
    "Moderate": "मध्यम",
    "Critical": "गंभीर",
    "Open": "खुला",
    "Closed": "बंद",
    "Online": "सक्रिय",
    "Offline": "निष्क्रिय",
    "Vegetative": "वानस्पतिक अवस्था",
    "Flowering": "पुष्पन अवस्था",
    "Seedling": "पौध अवस्था",
    "Harvest Ready": "कटाई के लिए तैयार",
    "Low": "कम",
    "Medium": "मध्यम",
    "High": "अधिक",

    // Weather Widget
    "Live Weather Data": "लाइव मौसम डेटा",
    "Using Last Available Weather Data": "अंतिम उपलब्ध मौसम डेटा का उपयोग",
    "Temperature": "तापमान",
    "Humidity": "आर्द्रता",
    "Wind Speed": "हवा की गति",
    "Rain Probability": "बारिश की संभावना",
    "Cloud Cover": "बादल का आवरण",
    "Sunrise": "सूर्योदय",
    "Sunset": "सूर्यास्त",

    // Compare Farms / Analytics
    "Compare Farms": "खेतों की तुलना",
    "Select Farm A": "खेत A चुनें",
    "Select Farm B": "खेत B चुनें",
    "Performance Comparison": "प्रदर्शन की तुलना",
    "Comparison Summary": "तुलना का सारांश",
    "Metrics": "मापदंड",
    "Health Score": "स्वास्थ्य स्कोर",
    "NDVI Index": "NDVI सूचकांक",

    // Reports & Settings Page
    "Download PDF": "पीडीएफ डाउनलोड करें",
    "Download CSV": "सीएसवी डाउनलोड करें",
    "Print": "प्रिंट करें",
    "Export Diagnostic Telemetry Logs": "डायग्नोस्टिक टेलीमेट्री लॉग निर्यात करें",
    "System Configuration": "सिस्टम कॉन्फ़िगरेशन",
    "Notifications": "सूचनाएं",
    "Agricultural Alerts": "कृषि अलर्ट",
    "unread diagnostic items": "अपठित नैदानिक अलर्ट",
    "No agricultural notifications active": "कोई सक्रिय कृषि सूचना नहीं है",
    "Mark all as read": "सभी पढ़े हुए के रूप में चिह्नित करें",
    "Clear": "साफ़ करें",

    // Scenario Simulator
    "Scenario Simulator": "परिदृश्य सिमुलेटर",
    "Awaiting Field Simulation": "खेत सिमुलेशन की प्रतीक्षा",
    "Select an active field target on the geospatial map to boot environmental scenario simulation tools.": "सक्रिय क्षेत्र परिदृश्य सिमुलेशन टूल शुरू करने के लिए मानचित्र पर एक खेत का चयन करें।",
    "Reset Engine": "इंजन रीसेट करें",
    "Simulated Inference": "सिम्युलेटेड निष्कर्ष",
    "Default Inference": "डिफ़ॉल्ट निष्कर्ष",
    "Recalculating AI Models...": "एआई मॉडल की पुनर्गणना की जा रही है...",
    "Yield prediction:": "उपज का अनुमान:",
    "Yield Prediction": "उपज का अनुमान",
    "Risk rating:": "जोखिम रेटिंग:",
    "Water Saved:": "बचाया गया पानी:",
    "Cost Saved:": "बचाई गई लागत:",
    "AI Confidence:": "एआई आत्मविश्वास:",
    "Rain Delayed 24h": "वर्षा २४ घंटे विलंबित",
    "Sets rain forecast probability to 0% due to weather front shift.": "मौसम के बदलाव के कारण बारिश का पूर्वानुमान 0% करता है।",
    "Temperature +3°C": "तापमान +३°सी",
    "Simulates microclimate thermal stress adding 3°C.": "३°सी जोड़कर सूक्ष्म जलवायु तापीय तनाव का अनुकरण करता है।",
    "Moisture Decreases 10%": "नमी १०% घटती है",
    "Simulates soil VWC moisture dropping by 10%.": "मिट्टी की नमी को १०% कम करता है।",
    "Water Supply Reduced 20%": "जल आपूर्ति २०% कम",
    "Forces dry irrigation channel flow, raising crop stress.": "सूखी सिंचाई नहर का अनुकरण करता है, जिससे फसल का तनाव बढ़ता है।",
    "Heavy Rainfall Tomorrow": "कल भारी बारिश",
    "Forecasts 90% rain probability tomorrow.": "कल ९०% बारिश की संभावना का अनुमान लगाता है।",

    // AI Insight Feed & System alerts
    "AI Insight Feed": "एआई अंतर्दृष्टि फीड",
    "AI Summary": "एआई सारांश",
    "Summary": "सारांश",
    "What-if Analysis": "संभावित विश्लेषण",
    "Current Scenario": "वर्तमान परिदृश्य",
    "Field Health": "खेत का स्वास्थ्य",
    "Crop Lifecycle": "फसल जीवनचक्र",
    "Irrigation Recommendation": "सिंचाई का सुझाव",
    "Fertilizer Recommendation": "उर्वरक का सुझाव",
    "Disease Alert": "रोग चेतावनी",
    "Weather Recommendation": "मौसम आधारित सुझाव",
    "Satellite Analysis": "सैटेलाइट विश्लेषण",
    "Vegetation Index": "वनस्पति सूचकांक",
    "Sensor Status": "सेंसर की स्थिति",
    "Telemetry Updated": "टेलीमेट्री अपडेटेड",
    "Success messages": "सफलतापूर्वक संपन्न",
    "Loading messages": "लोड हो रहा है...",
    "Empty state messages": "कोई डेटा उपलब्ध नहीं",

    // PDF and CSV export layouts
    "PRECISION WATER INTELLIGENCE REPORT": "परिशुद्ध जल आसूचना रिपोर्ट",
    "PRECISION TELEMETRY DIAGNOSTIC PROFILE": "परिशुद्ध टेलीमेट्री नैदानिक विवरण",
    "AI INTELLIGENCE DIAGNOSTIC DECISION": "एआई इंटेलिजेंस नैदानिक निर्णय",
    "Farm / Field ID:": "खेत / फ़ील्ड आईडी:",
    "Region State:": "राज्य:",
    "District Hub:": "जिला केंद्र:",
    "Active Crop Profile:": "सक्रिय फसल विवरण:",
    "Field Size Area:": "खेत का क्षेत्रफल:",
    "Soil Profile Silt:": "मिट्टी का प्रकार:",
    "NDVI Vegetation Index:": "NDVI वनस्पति सूचकांक:",
    "Soil Moisture VWC:": "मिट्टी की नमी VWC:",
    "Climate Conditions:": "जलवायु परिस्थितियां:",
    "Crop Health Rating:": "फसल स्वास्थ्य रेटिंग:",
    "AI Recommendation:": "एआई सुझाव:",
    "Action Plan:": "कार्य योजना:",
    "Expected Impact:": "अपेक्षित प्रभाव:",
    "Scenario Calibration:": "परिदृश्य सारांश:",
    "Water Saving Estimate:": "जल बचत अनुमान:",
    "Generated:": "तैयार किया गया:",
    "System: Live Satellite Sync": "सिस्टम: लाइव सैटेलाइट सिंक",

    // Dynamic mock profiles
    "Awaiting Target Asset": "चयनित खेत की प्रतीक्षा",
    "Select a precision field polygon on the geospatial map to initiate Edge AI telemetry and soil diagnostics.": "सक्रिय क्षेत्र परिदृश्य सिमुलेशन टूल शुरू करने के लिए मानचित्र पर एक खेत का चयन करें।",
    "Edge AI Active": "एज एआई ऑनलाइन",
    "Crop Health Matrix": "फसल की स्थिति",
    "Vegetation density index rating.": "वनस्पति घनत्व सूचकांक रेटिंग।",
    "Saved": "की बचत",
    "Telemetry Node:": "टेलीमेट्री नोड:",
    "General Regional Averages": "सामान्य क्षेत्रीय औसत",
    "District": "जिला",
    "Historical Telemetry": "ऐतिहासिक टेलीमेट्री",
    "Field vegetation displays high chlorophyll concentration and optimized moisture index. Transpiration demands are normal. Irrigation hold is advised for the next 24 hours to prevent nutrient runoff.": "खेत की वनस्पति उच्च क्लोरोफिल एकाग्रता और अनुकूलित नमी सूचकांक प्रदर्शित करती है। वाष्पोत्सर्जन की मांग सामान्य है। पोषक तत्वों के बहाव को रोकने के लिए अगले 24 घंटों के लिए सिंचाई रोकने की सलाह दी जाती है।",
    "Moderate moisture deficit identified in shallow root zones. Weather forecasts indicate rising temperatures. Short-duration pulse valving is recommended to maintain volumetric saturation.": "उथले जड़ क्षेत्रों में मध्यम नमी की कमी की पहचान की गई है। मौसम के पूर्वानुमान से तापमान बढ़ने का संकेत मिलता है। नाममात्र वॉल्यूमेट्रिक संतृप्ति बनाए रखने के लिए कम अवधि के पल्स वाल्विंग की सिफारिश की जाती है।",
    "Critical soil dehydration anomalies verified. VWC has collapsed past warning thresholds (30%). High priority valving override is required immediately to mitigate yield degradation risks.": "गंभीर मिट्टी के निर्जलीकरण विसंगतियों का सत्यापन किया गया। VWC चेतावनी सीमा (30%) को पार कर गया है। उपज में गिरावट के जोखिम को कम करने के लिए तुरंत उच्च प्राथमिकता वाले वाल्विंग ओवरराइड की आवश्यकता है।",
    "Hold Irrigation. VWC Saturation targets met.": "सिंचाई रोकें। VWC संतृप्ति लक्ष्य पूरे हुए।",
    "Pulse Irrigation (12 mins, Scheduled at 4 PM).": "पल्स सिंचाई (12 मिनट, शाम 4 बजे निर्धारित)।",
    "Trigger High-Flow Hydration Override immediately.": "तुरंत उच्च-प्रवाह जलयोजन ओवरराइड शुरू करें।",

    // AI templates
    "Soil moisture is below the recommended threshold.": "मिट्टी की नमी अनुशंसित स्तर से कम है।",
    "Irrigation is recommended within 24 hours.": "अगले 24 घंटों के भीतर सिंचाई करने की सलाह दी जाती है।",
    "Rain is expected tomorrow.": "कल वर्षा होने की संभावना है।",
    "Crop health is excellent.": "फसल की स्थिति उत्कृष्ट है।",
    "Monitor for pest activity.": "कीट गतिविधि पर निगरानी रखें।"
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en')

  const t = (key) => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
