import React, { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { Copy, RefreshCw, MessageSquare, Check } from 'lucide-react'
import { useLanguage } from '../../context/LanguageContext'

const SMSAdvisoryCard = () => {
  const { t, language } = useLanguage()
  const isHindi = language === 'hi'
  const [selectedFarm, setSelectedFarm] = useState(null)
  const [metrics, setMetrics] = useState(null)
  const [copied, setCopied] = useState(false)
  const [timestamp, setTimestamp] = useState('')

  // Load telemetry data on mount and reactively
  const loadData = () => {
    try {
      const farm = JSON.parse(localStorage.getItem('selectedFarm') || 'null')
      const met = JSON.parse(localStorage.getItem('selectedFarmMetrics') || 'null')
      setSelectedFarm(farm)
      setMetrics(met)
      
      const now = new Date()
      const timeStr = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      const dateStr = now.toLocaleDateString([], { month: 'short', day: 'numeric' })
      setTimestamp(`${dateStr}, ${timeStr}`)
    } catch (err) {
      console.error('Error loading localStorage inside SMSAdvisoryCard:', err)
    }
  }

  useEffect(() => {
    loadData()
    // Sync on local storage storage events
    window.addEventListener('storage', loadData)
    // Sync on active farm diagnostics event trigger
    window.addEventListener('farmAnalyzed', loadData)

    return () => {
      window.removeEventListener('storage', loadData)
      window.removeEventListener('farmAnalyzed', loadData)
    }
  }, [])

  const cropTranslations = {
    paddy: 'धान',
    rice: 'धान',
    wheat: 'गेहूं',
    cotton: 'कपास',
    sugarcane: 'गन्ना',
    barley: 'जौ',
    millets: 'बाजरा',
    bajra: 'बाजरा',
    potato: 'आलू',
    maize: 'मक्का',
    saffron: 'केसर',
    tea: 'चाय',
    cardamom: 'इलायची',
    cashew: 'काजू',
    spices: 'मसाले'
  }

  const getTranslatedCrop = (cropName) => {
    if (!cropName) return 'N/A'
    const key = cropName.toLowerCase().split(' ')[0]
    return cropTranslations[key] || cropName
  }

  const getTranslatedPriority = (pri) => {
    if (!pri) return isHindi ? 'मध्यम' : 'MEDIUM'
    const p = pri.toUpperCase()
    if (p === 'CRITICAL' || p === 'HIGH') return isHindi ? 'उच्च' : 'HIGH'
    if (p === 'MEDIUM' || p === 'NORMAL') return isHindi ? 'मध्यम' : 'MEDIUM'
    return isHindi ? 'कम' : 'LOW'
  }

  // Generate dynamic SMS advisory text using live values
  const generateSmsText = () => {
    if (!selectedFarm || !metrics) return ''

    const farmId = selectedFarm.id || 'N/A'
    const cropName = isHindi ? getTranslatedCrop(selectedFarm.crop) : (selectedFarm.crop || 'N/A')
    const moistureVal = parseFloat(selectedFarm.moisture) || 35
    const rainProbability = parseFloat(metrics.rainProbability) || 10
    const priorityText = getTranslatedPriority(metrics.priority)

    // Parse water savings percentage cleanly
    let savingText = isHindi ? '22%' : '22%'
    if (metrics.waterSaving) {
      const match = metrics.waterSaving.match(/\d+/)
      if (match) {
        // Translate visual litres to indicative percentage or keep as calculated
        const lit = parseInt(match[0])
        const percentage = Math.min(35, Math.max(12, 10 + (lit % 25)))
        savingText = `${percentage}%`
      }
    }

    let moistureLine = ''
    if (moistureVal < 30) {
      moistureLine = isHindi ? '⚠ मिट्टी की नमी कम है।' : '⚠ Soil moisture is low.'
    } else if (moistureVal >= 30 && moistureVal < 45) {
      moistureLine = isHindi ? '⚠ मिट्टी की नमी मध्यम है।' : '⚠ Soil moisture is moderate.'
    } else {
      moistureLine = isHindi ? '⚠ मिट्टी की नमी इष्टतम है।' : '⚠ Soil moisture is optimal.'
    }

    let rainLine = ''
    if (rainProbability > 50) {
      rainLine = isHindi ? '🌧 कल वर्षा होने की संभावना है।' : '🌧 Rain expected tomorrow.'
    } else {
      rainLine = isHindi ? '🌧 भारी बारिश की संभावना नहीं है।' : '🌧 No heavy rain expected.'
    }

    let irrigationLine = ''
    if (rainProbability > 50) {
      irrigationLine = isHindi ? '💧 आज सिंचाई की आवश्यकता नहीं है।' : '💧 Delay irrigation for 1 day.'
    } else if (moistureVal < 30) {
      irrigationLine = isHindi ? '💧 तुरंत सिंचाई करने की सलाह दी जाती है।' : '💧 Irrigation is recommended immediately.'
    } else {
      irrigationLine = isHindi ? '💧 नियमित सिंचाई कार्यक्रम बनाए रखें।' : '💧 Maintain regular irrigation schedule.'
    }

    if (isHindi) {
      return `AgriX स्मार्ट सूचना\n\nखेत: ${farmId}\nफसल: ${cropName}\n\n${moistureLine}\n${rainLine}\n${irrigationLine}\n\nअनुमानित जल बचत: ${savingText}\nप्राथमिकता: ${priorityText}\n\nAgriX AI`
    } else {
      return `AgriX Smart Advisory\n\nFarm: ${farmId}\nCrop: ${cropName}\n\n${moistureLine}\n${rainLine}\n${irrigationLine}\n\nEstimated Water Saving: ${savingText}\nPriority: ${priorityText}\n\nGenerated by AgriX AI`
    }
  }

  const smsText = generateSmsText()

  const handleCopy = () => {
    if (!smsText) return
    navigator.clipboard.writeText(smsText)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="w-full h-full rounded-2xl border border-white/5 bg-[#050816]/40 backdrop-blur-md shadow-2xl p-5 flex flex-col justify-between select-none">
      
      {/* Header Info */}
      <div className="text-left border-b border-white/5 pb-3.5 mb-3.5">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-400">
              <MessageSquare className="h-4.5 w-4.5" />
            </div>
            <h3 className="font-bold text-slate-100 text-sm tracking-wide font-sans">
              {isHindi ? '📱 एसएमएस सलाहकार पूर्वावलोकन' : '📱 SMS Advisory Preview'}
            </h3>
          </div>
          {selectedFarm && metrics && (
            <span className="text-[9px] font-black uppercase tracking-wider px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
              {isHindi ? 'भेजने के लिए तैयार' : 'Ready to Send'}
            </span>
          )}
        </div>
        <p className="text-[10px] text-slate-400 mt-1">
          {isHindi ? '"यह संदेश किसान को भेजा जाएगा।"' : '"This message would be delivered to the farmer."'}
        </p>
      </div>

      {/* Main Content Area */}
      {selectedFarm && metrics ? (
        <div className="space-y-3.5 flex-1 flex flex-col justify-between">
          
          {/* Metadata Grid */}
          <div className="grid grid-cols-2 gap-3 text-left bg-white/2 border border-white/5 rounded-xl p-3 text-[10px] font-semibold text-slate-400">
            <div>
              <span className="text-[9px] text-slate-500 uppercase block font-black">{isHindi ? 'किसान' : 'Farmer'}</span>
              <span className="text-slate-200 mt-0.5 block truncate">{selectedFarm.farmerName || (isHindi ? 'कृषि प्रशासक' : 'Farm Administrator')}</span>
            </div>
            <div>
              <span className="text-[9px] text-slate-500 uppercase block font-black">{isHindi ? 'क्षेत्र / जिला' : 'District'}</span>
              <span className="text-slate-200 mt-0.5 block truncate">{selectedFarm.district || selectedFarm.name?.split(' ')[0]}</span>
            </div>
            <div>
              <span className="text-[9px] text-slate-500 uppercase block font-black">{isHindi ? 'समय' : 'Timestamp'}</span>
              <span className="text-slate-200 mt-0.5 block truncate font-mono text-[9px]">{timestamp}</span>
            </div>
            <div>
              <span className="text-[9px] text-slate-500 uppercase block font-black">{isHindi ? 'वितरण चैनल' : 'Delivery Channel'}</span>
              <span className="text-emerald-400 mt-0.5 block font-bold">{isHindi ? 'एसएमएस पूर्वावलोकन' : 'SMS Preview'}</span>
            </div>
          </div>

          {/* SMS Display Screen (Simulated Mobile Bubble) */}
          <div className="relative flex-1 bg-[#090e22]/60 rounded-2xl p-4 border border-white/5 min-h-[160px] flex flex-col justify-between text-left">
            <div className="whitespace-pre-line text-xs font-semibold text-slate-200 leading-relaxed font-sans font-medium">
              {smsText}
            </div>
            <div className="absolute top-2 right-2 w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
          </div>

          {/* Interaction controls */}
          <div className="grid grid-cols-2 gap-3 pt-2">
            <button
              onClick={loadData}
              className="flex items-center justify-center gap-1.5 px-3 py-2 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 text-slate-300 font-bold text-xs transition-all cursor-pointer"
            >
              <RefreshCw className="h-3.5 w-3.5" />
              {isHindi ? 'अपडेट करें' : 'Generate SMS'}
            </button>
            <button
              onClick={handleCopy}
              className={`flex items-center justify-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer
                ${copied 
                  ? 'bg-emerald-500 text-[#050816]' 
                  : 'bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 hover:bg-emerald-500/20'
                }
              `}
            >
              {copied ? (
                <>
                  <Check className="h-3.5 w-3.5" />
                  {isHindi ? 'कॉपी हो गया' : 'Copied!'}
                </>
              ) : (
                <>
                  <Copy className="h-3.5 w-3.5" />
                  {isHindi ? 'कॉपी करें' : 'Copy Message'}
                </>
              )}
            </button>
          </div>

        </div>
      ) : (
        <div className="flex-1 flex flex-col items-center justify-center py-8 text-center bg-white/2 border border-white/5 rounded-xl min-h-[220px]">
          <div className="p-3 rounded-full bg-blue-500/10 border border-blue-500/20 text-slate-400 mb-3 animate-pulse">
            <MessageSquare className="h-6 w-6" />
          </div>
          <h4 className="font-bold text-slate-300 text-xs">
            {isHindi ? 'एसएमएस पूर्वावलोकन उपलब्ध नहीं है' : 'SMS Preview Unavailable'}
          </h4>
          <p className="text-[10px] text-slate-500 leading-normal mt-1 max-w-[200px]">
            {isHindi 
              ? 'जानकारी प्राप्त करने के लिए कृपया पहले डैशबोर्ड पर किसी खेत का चयन करें।' 
              : 'Please select a farm on the dashboard map first to generate the SMS preview.'
            }
          </p>
        </div>
      )}

    </div>
  )
}

export default SMSAdvisoryCard
